# SysBound Cx — connect live frontend to Render API
# Run from project root: .\scripts\setup-live.ps1

param(
  [string]$ApiUrl = ""
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "SysBound Cx — Live setup helper" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

if (-not $ApiUrl) {
  Write-Host "Step 1: Deploy backend on Render (one-time, ~5 min)" -ForegroundColor Yellow
  Write-Host "  Open this link and sign in with GitHub:" -ForegroundColor White
  Write-Host "  https://render.com/deploy?repo=https://github.com/Mchavez31/SysBound-Cx" -ForegroundColor Green
  Write-Host ""
  Write-Host "  Wait until the web service shows 'Live'." -ForegroundColor White
  Write-Host "  Copy your API URL (example: https://sysbound-cx-api.onrender.com)" -ForegroundColor White
  Write-Host ""
  $ApiUrl = Read-Host "Paste your Render API URL (without /api)"
}

$ApiUrl = $ApiUrl.Trim().TrimEnd("/")
if ($ApiUrl -match "/api$") {
  $ApiBase = $ApiUrl
  $ApiUrl = $ApiUrl -replace "/api$", ""
} else {
  $ApiBase = "$ApiUrl/api"
}

Write-Host ""
Write-Host "Testing API health at $ApiBase/health ..." -ForegroundColor Cyan
try {
  $health = Invoke-RestMethod -Uri "$ApiBase/health" -Method GET -TimeoutSec 60
  Write-Host "  OK: $($health | ConvertTo-Json -Compress)" -ForegroundColor Green
} catch {
  Write-Host "  API not responding yet. Render free tier may be waking up — wait 30s and retry." -ForegroundColor Red
  Write-Host "  $($_.Exception.Message)" -ForegroundColor Red
  exit 1
}

Write-Host ""
Write-Host "Step 2: Set GitHub Actions variable VITE_API_URL" -ForegroundColor Yellow
Write-Host "  1. Open: https://github.com/Mchavez31/SysBound-Cx/settings/variables/actions" -ForegroundColor Green
Write-Host "  2. New repository variable:" -ForegroundColor White
Write-Host "       Name:  VITE_API_URL" -ForegroundColor White
Write-Host "       Value: $ApiBase" -ForegroundColor White
Write-Host "  3. Open: https://github.com/Mchavez31/SysBound-Cx/actions/workflows/deploy-pages.yml" -ForegroundColor Green
Write-Host "  4. Click 'Run workflow' to redeploy the frontend" -ForegroundColor White
Write-Host ""
Write-Host "Live site after deploy: https://mchavez31.github.io/SysBound-Cx/" -ForegroundColor Cyan
Write-Host ""

# Also write local production env for reference
$envFile = Join-Path $PSScriptRoot "..\frontend\.env.production"
@"
# Auto-generated by setup-live.ps1 — used for local production builds
VITE_API_URL=$ApiBase
"@ | Set-Content -Path $envFile -Encoding UTF8
Write-Host "Wrote $envFile (for local reference; GitHub uses the Actions variable above)" -ForegroundColor DarkGray
